export enum UserRole {
  ADMIN = 'ADMIN',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  DEVELOPER = 'DEVELOPER',
  DESIGNER = 'DESIGNER',
  TESTER = 'TESTER',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  TEAM_MEMBER = 'TEAM_MEMBER',
  CLIENT = 'CLIENT',
  RH = 'RH',
  AURA_AI = 'AURA_AI',
  ROOT = 'ROOT',
}

export const USER_ROLES = Object.values(UserRole);

