export enum LeaveStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  CHEF_APPROVED = "CHEF_APPROVED",
  FULLY_APPROVED = "FULLY_APPROVED",
  REJECTED = "REJECTED",
}

export enum LeaveType {
  ANNUAL = "ANNUAL",
  SICK = "SICK",
  PERSONAL = "PERSONAL",
  MATERNITY = "MATERNITY",
  PATERNITY = "PATERNITY",
  UNPAID = "UNPAID",
}

export enum LeaveRole {
  EMPLOYEE = "EMPLOYEE",
  MANAGER = "MANAGER",
  HR_ADMIN = "HR_ADMIN",
  ADMIN = "ADMIN",
  ROOT = "ROOT",
  SUPERADMIN = "SUPERADMIN",
  SUPER_ADMIN = "SUPER_ADMIN",
  // Business roles — treated as employees for HR purposes
  DEVELOPER = "DEVELOPER",
  DESIGNER = "DESIGNER",
  TESTER = "TESTER",
  PROJECT_MANAGER = "PROJECT_MANAGER",
  TEAM_MEMBER = "TEAM_MEMBER",
}

